feat: add service codegen framework
aws/smithy-go pull request #497
Opened 2024-02-06 20:44 UTC by lucix-aws

Adds the infrastructure for service code generation.

Service codegen exists as a separate plugin which is powered by the newer recommended `DirectedCodegen`.

This PR adds partial support for the awsJson1.0 protocol. The document type and event stream operations are not yet implemented.

Special thanks to @syall and @isaiahvita without whom this would not have been possible!

2024-02-12 18:16 UTC, isaiahvita commented on codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/ServiceDirectedCodegen.java
> +public class ServiceDirectedCodegen implements DirectedCodegen<GoCodegenContext, GoSettings, GoServiceIntegration> {
documentation for all public classes?

2024-02-12 18:37 UTC, syall commented on codegen/smithy-go-codegen-test/smithy-build.json
> +            "module": "github.com/aws/smithy-go/internal/tests/service/weather",
I think we can just rename the module to `server/weather`:

```suggestion
            "module": "github.com/aws/smithy-go/internal/tests/server/weather",
```

For the `go-codegen` -> `go-client-codegen` plugin rename, this is included in this draft PR here for reference: https://github.com/aws/smithy-go/pull/468

2024-02-12 21:08 UTC, syall requested changes
General comments:

- Rather than "Service", I think "Server" is a better name. This avoids any naming confusion for Service shapes, and is the recommended way to name Smithy plugins: https://smithy.io/2.0/guides/building-codegen/configuring-the-generator.html#how-to-name-codegen-plugins
- The Server plugin using DirectedCodegen is awesome. I think unifying the Go Integration interfaces would be better in the long term, especially if we want to write integrations that are applicable to both client / server codegen. Keeping `ArtifactType` for nullable index check modes makes sense though.
- nit: For all of the classes with changes in visibility, I am wondering if we should move them to an `internal` package also, just to be sure no one uses it. Either way, we should be liberal with using the `@SmithyInternalApi` annotation.

2024-02-26 16:17 UTC, lucix-aws commented on codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/protocol/aws/AwsJson10ProtocolGenerator.java
> +        var errorShapes = ctx.model().getStructureShapesWithTrait(ErrorTrait.class);
`// FUTURE` for now, IMO.

2024-02-26 16:18 UTC, lucix-aws commented on codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/ServiceDirectedCodegen.java
> +        }
Unclear, this was taken from the client version.

2024-02-26 16:21 UTC, lucix-aws commented on codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/ServiceDirectedCodegen.java
> +        }
Marked as FUTURE to reconcile

2024-02-27 00:21 UTC, syall approved these changes

2024-02-27 00:21 UTC, syall commented on codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoSettings.java
> +    }
I don't think `ArtifactType` is doing anything meaningful right now, it can be removed.

2024-03-01 15:42 UTC, merged